In [1]:
import torch

# Convert a vector of numbers to a matrix by repeating elements

In [2]:
a = torch.arange(5)
print(a)

tensor([0, 1, 2, 3, 4])


In [3]:
a.shape

torch.Size([5])

## The first way 

Let's make a 5 x 4 matrix with these elements repeated in each row.

In [4]:
t = a.view((5,1)).expand(-1, 4)
print(t.shape)

torch.Size([5, 4])


`expand` can expand a singleton dimension.

In [5]:
print(t)

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])


In [6]:
t = t.unsqueeze(0)
print(t.shape)

torch.Size([1, 5, 4])


## The second way

In [7]:
r = torch.tile(a.view((5,1)), (1, 4))
print(r.shape)

torch.Size([5, 4])


In [8]:
print(r)

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4]])
