In [1]:
# First, import PyTorch
import torch

In [2]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [3]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

> **Exercise**: Calculate the output of the network with input features `features`, weights `weights`, and bias `bias`. Similar to Numpy, PyTorch has a [`torch.sum()`](https://pytorch.org/docs/stable/torch.html#torch.sum) function, as well as a `.sum()` method on tensors, for taking sums. Use the function `activation` defined above as the activation function.

In [4]:
### Solution
y = activation(torch.sum(features * weights) + bias)
y = activation((features * weights).sum() + bias)

A better way is to use matrix multiplication

Use [`torch.mm()`](https://pytorch.org/docs/stable/torch.html#torch.mm) or [`torch.matmul()`](https://pytorch.org/docs/stable/torch.html#torch.matmul) for matrix multiplication.

To change the shape use:
- `weights.reshape(a, b)`: may return a copy or a view of the original tensor.
- `weights.resize_(a, b)`
- `weights.view(a, b)`: will return a new tensor with the same data as `weights` with size `(a, b)`. The returned tensor will share the underling data with the original tensor.

Practical Tip: 
To reshape, use `view`. And, to copy a tensor, use `clone`. [here](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch)


> **Exercise**: Calculate the output of our little network using matrix multiplication.

In [5]:
## Solution
y = activation(torch.mm(features, weights.view(5,1)) + bias) # mm and view are the best options from the above.

### Stack them up!
$$
y =  f_2 \! \left(\, f_1 \! \left(\vec{x} \, \mathbf{W_1}\right) \mathbf{W_2} \right)
$$

> **Exercise:** Calculate the output for this multi-layer network using the weights `W1` & `W2`, and the biases, `B1` & `B2`. 

In [6]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [7]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[ 0.3171]])


## Numpy to Torch and back

To create a tensor from a Numpy array, use `torch.from_numpy()`. 

To convert a tensor to a Numpy array, use the `.numpy()` method.

In [7]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.55170566, 0.12686235, 0.81197184],
       [0.49593213, 0.40170161, 0.25362679],
       [0.38455833, 0.15535196, 0.7377223 ],
       [0.32062595, 0.23301023, 0.72929018]])

In [8]:
b = torch.from_numpy(a)
b

tensor([[0.5517, 0.1269, 0.8120],
        [0.4959, 0.4017, 0.2536],
        [0.3846, 0.1554, 0.7377],
        [0.3206, 0.2330, 0.7293]], dtype=torch.float64)

In [9]:
b.numpy()

array([[0.55170566, 0.12686235, 0.81197184],
       [0.49593213, 0.40170161, 0.25362679],
       [0.38455833, 0.15535196, 0.7377223 ],
       [0.32062595, 0.23301023, 0.72929018]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [10]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[1.1034, 0.2537, 1.6239],
        [0.9919, 0.8034, 0.5073],
        [0.7691, 0.3107, 1.4754],
        [0.6413, 0.4660, 1.4586]], dtype=torch.float64)

In [11]:
# Numpy array matches new values from Tensor
a

array([[1.10341133, 0.25372469, 1.62394367],
       [0.99186427, 0.80340323, 0.50725358],
       [0.76911666, 0.31070392, 1.4754446 ],
       [0.64125189, 0.46602047, 1.45858035]])